### ISSUE TITLE
javadoc not showing up

### ISSUE THREAD

**Issue by rmros** [servicecatalog/oscm-interfaces#28]
[see javadoc]  not published at jitpack, please review it ,

**Comment by GoebelL** [comment]
Hi @rmros 
Thank you for pointing this out. This should be fixed now.

**Comment by rmros** [comment]
im thank you fix it that, 
but still not showing up its show just empty page

**Comment by GoebelL** [comment]
Sorry, there is still some issue with extraction on jitpack. I am on it.

For the time beeing, there you can use following workaround:
1. Copy the link address from the '[source]' link and open in an editor.
2. Change the address from "...-SNAPSHOT-sources.jar" to "...-SNAPSHOT-javadoc.jar" and paste the link into your browser
3. Download, extract the jar file and open the index page 

E.g.: https://jitpack.io/com/github/servicecatalog/oscm-interfaces/oscm-extsvc/master-SNAPSHOT/oscm-extsvc-master-SNAPSHOT-javadoc.jar

https://jitpack.io/com/github/servicecatalog/oscm-interfaces/oscm-extsvc/master-SNAPSHOT/oscm-extsvc-master-SNAPSHOT-javadoc.jar
